[package]
name = "rust_jwt"
version = "0.1.0"
edition = "2021"

[dependencies]
jsonwebtoken = "8.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4"
clap = { version = "4.0", features = ["derive"] }

